;; domain file: blocksworld-domain-complete.pddl
(define (domain blocks-domain)
	(:requirements :strips)
	(:predicates    (clear ?x)
		            (on-table ?x)
					(holding ?x ?y)
					(on ?x ?y)
					(free ?x)
	)
	(:action pickup
		:parameters (?hand ?ob)
		:precondition (and (clear ?ob) (on-table ?ob) (free ?hand))
		:effect (and (not (clear ?ob))
				     (not (on-table ?ob))
				     (holding ?hand ?ob)
					 (not (free ?hand))
				)
	)
	(:action putdown
		:parameters (?hand ?ob)
		:precondition (holding ?hand ?ob)
		:effect (and (on-table ?ob)
					 (clear ?ob)
					 (not (holding ?hand ?ob))
					 (free ?hand)
				)
	)
	(:action unstack
		:parameters (?hand ?ob ?y)
		:precondition (and (on ?ob ?Y) (clear ?ob) (free ?hand))
		:effect (and (not (on ?ob ?y))
		             (not (clear ?ob))
					 (clear ?y)
					 (not (free ?hand))
					 (holding ?hand ?ob)
				)
	)
	(:action stack
		:parameters (?hand ?ob ?y)
		:precondition (and (holding ?hand ?ob) (clear ?y))
		:effect (and (on ?ob ?y)
					 (clear ?ob)
					 (not (holding ?hand ?ob))
					 (free ?hand)
				)
	)
)